//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 08:53:05 AM CDT 
//


package com.amazonaws.s3.doc._2006_03_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateBucketConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateBucketConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LocationConstraint" type="{http://s3.amazonaws.com/doc/2006-03-01/}LocationConstraint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateBucketConfiguration", propOrder = {
    "locationConstraint"
})
@XmlRootElement(name = "CreateBucketConfiguration")
public class CreateBucketConfiguration {

    @XmlElement(name = "LocationConstraint", required = true)
    protected LocationConstraint locationConstraint;

    /**
     * Gets the value of the locationConstraint property.
     * 
     * @return
     *     possible object is
     *     {@link LocationConstraint }
     *     
     */
    public LocationConstraint getLocationConstraint() {
        return locationConstraint;
    }

    /**
     * Sets the value of the locationConstraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationConstraint }
     *     
     */
    public void setLocationConstraint(LocationConstraint value) {
        this.locationConstraint = value;
    }

}
