//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.14 at 10:25:25 AM EDT
//

package com.amazonaws.ec2.doc._2015_10_01;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.amazonaws.ec2.doc._2015_10_01 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java
 * representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type
 * definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory
{

    private final static QName _DescribeVpcsResponse_QNAME =
            new QName("http://ec2.amazonaws.com/doc/2015-10-01/", "DescribeVpcsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * com.amazonaws.ec2.doc._2015_10_01
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link DescribeVpcsResponseType }
     */
    public DescribeVpcsResponseType createDescribeVpcsResponseType()
    {
        return new DescribeVpcsResponseType();
    }

    /**
     * Create an instance of {@link ResourceTagSetItemType }
     */
    public ResourceTagSetItemType createResourceTagSetItemType()
    {
        return new ResourceTagSetItemType();
    }

    /**
     * Create an instance of {@link ResourceTagSetType }
     */
    public ResourceTagSetType createResourceTagSetType()
    {
        return new ResourceTagSetType();
    }

    /**
     * Create an instance of {@link VpcType }
     */
    public VpcType createVpcType()
    {
        return new VpcType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescribeVpcsResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://ec2.amazonaws.com/doc/2015-10-01/", name = "DescribeVpcsResponse")
    public JAXBElement<DescribeVpcsResponseType> createDescribeVpcsResponse(DescribeVpcsResponseType value)
    {
        return new JAXBElement<DescribeVpcsResponseType>(_DescribeVpcsResponse_QNAME, DescribeVpcsResponseType.class, null,
                value);
    }

}
