//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.14 at 10:25:25 AM EDT
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ec2.amazonaws.com/doc/2015-10-01/",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.amazonaws.ec2.doc._2015_10_01;
