//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.17 at 01:23:02 PM CST 
//


package com.amazonaws.rds.doc._2010_07_28;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://rds.amazonaws.com/doc/2014-09-01/}CreateDBInstanceResult"/>
 *         &lt;element ref="{http://rds.amazonaws.com/doc/2014-09-01/}ResponseMetadata"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createDBInstanceResult",
    "responseMetadata"
})
@XmlRootElement(name = "CreateDBInstanceResponse")
public class CreateDBInstanceResponse {

    @XmlElement(name = "CreateDBInstanceResult", required = true)
    protected CreateDBInstanceResult createDBInstanceResult;
    @XmlElement(name = "ResponseMetadata", required = true)
    protected ResponseMetadata responseMetadata;

    /**
     * Gets the value of the createDBInstanceResult property.
     * 
     * @return
     *     possible object is
     *     {@link CreateDBInstanceResult }
     *     
     */
    public CreateDBInstanceResult getCreateDBInstanceResult() {
        return createDBInstanceResult;
    }

    /**
     * Sets the value of the createDBInstanceResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateDBInstanceResult }
     *     
     */
    public void setCreateDBInstanceResult(CreateDBInstanceResult value) {
        this.createDBInstanceResult = value;
    }

    /**
     * Gets the value of the responseMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMetadata }
     *     
     */
    public ResponseMetadata getResponseMetadata() {
        return responseMetadata;
    }

    /**
     * Sets the value of the responseMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMetadata }
     *     
     */
    public void setResponseMetadata(ResponseMetadata value) {
        this.responseMetadata = value;
    }

}
