//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.01 at 08:18:37 AM CDT 
//


package com.amazonaws.rds.doc._2010_07_28;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                     <p>
 *             
 *                     </p>
 *                 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBParameterGroup" type="{http://rds.amazonaws.com/doc/2010-07-28/}DBParameterGroup"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbParameterGroup"
})
@XmlRootElement(name = "CreateDBParameterGroupResult")
public class CreateDBParameterGroupResult {

    @XmlElement(name = "DBParameterGroup", required = true)
    protected DBParameterGroup dbParameterGroup;

    /**
     * Gets the value of the dbParameterGroup property.
     * 
     * @return
     *     possible object is
     *     {@link DBParameterGroup }
     *     
     */
    public DBParameterGroup getDBParameterGroup() {
        return dbParameterGroup;
    }

    /**
     * Sets the value of the dbParameterGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBParameterGroup }
     *     
     */
    public void setDBParameterGroup(DBParameterGroup value) {
        this.dbParameterGroup = value;
    }

}
