//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.17 at 01:23:02 PM CST 
//


package com.amazonaws.rds.doc._2010_07_28;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                   <p>
 *           
 *                   </p>
 *               
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DBInstanceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AllocatedStorage" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="DBInstanceClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Engine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MasterUsername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MasterUserPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DBSecurityGroups" type="{http://rds.amazonaws.com/doc/2014-09-01/}DBSecurityGroupNameList" minOccurs="0"/>
 *         &lt;element name="VpcSecurityGroupIds" type="{http://rds.amazonaws.com/doc/2014-09-01/}VpcSecurityGroupIdList" minOccurs="0"/>
 *         &lt;element name="AvailabilityZone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DBSubnetGroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreferredMaintenanceWindow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DBParameterGroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BackupRetentionPeriod" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="PreferredBackupWindow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MultiAZ" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EngineVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoMinorVersionUpgrade" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LicenseModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Iops" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="OptionGroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CharacterSetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PubliclyAccessible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Tags" type="{http://rds.amazonaws.com/doc/2014-09-01/}TagList" minOccurs="0"/>
 *         &lt;element name="StorageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TdeCredentialArn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TdeCredentialPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbName",
    "dbInstanceIdentifier",
    "allocatedStorage",
    "dbInstanceClass",
    "engine",
    "masterUsername",
    "masterUserPassword",
    "dbSecurityGroups",
    "vpcSecurityGroupIds",
    "availabilityZone",
    "dbSubnetGroupName",
    "preferredMaintenanceWindow",
    "dbParameterGroupName",
    "backupRetentionPeriod",
    "preferredBackupWindow",
    "port",
    "multiAZ",
    "engineVersion",
    "autoMinorVersionUpgrade",
    "licenseModel",
    "iops",
    "optionGroupName",
    "characterSetName",
    "publiclyAccessible",
    "tags",
    "storageType",
    "tdeCredentialArn",
    "tdeCredentialPassword"
})
@XmlRootElement(name = "CreateDBInstance")
public class CreateDBInstance {

    @XmlElement(name = "DBName")
    protected String dbName;
    @XmlElement(name = "DBInstanceIdentifier", required = true)
    protected String dbInstanceIdentifier;
    @XmlElement(name = "AllocatedStorage", required = true)
    protected BigInteger allocatedStorage;
    @XmlElement(name = "DBInstanceClass", required = true)
    protected String dbInstanceClass;
    @XmlElement(name = "Engine", required = true)
    protected String engine;
    @XmlElement(name = "MasterUsername", required = true)
    protected String masterUsername;
    @XmlElement(name = "MasterUserPassword", required = true)
    protected String masterUserPassword;
    @XmlElement(name = "DBSecurityGroups")
    protected DBSecurityGroupNameList dbSecurityGroups;
    @XmlElement(name = "VpcSecurityGroupIds")
    protected VpcSecurityGroupIdList vpcSecurityGroupIds;
    @XmlElement(name = "AvailabilityZone")
    protected String availabilityZone;
    @XmlElement(name = "DBSubnetGroupName")
    protected String dbSubnetGroupName;
    @XmlElement(name = "PreferredMaintenanceWindow")
    protected String preferredMaintenanceWindow;
    @XmlElement(name = "DBParameterGroupName")
    protected String dbParameterGroupName;
    @XmlElement(name = "BackupRetentionPeriod")
    protected BigInteger backupRetentionPeriod;
    @XmlElement(name = "PreferredBackupWindow")
    protected String preferredBackupWindow;
    @XmlElement(name = "Port")
    protected BigInteger port;
    @XmlElement(name = "MultiAZ")
    protected Boolean multiAZ;
    @XmlElement(name = "EngineVersion")
    protected String engineVersion;
    @XmlElement(name = "AutoMinorVersionUpgrade")
    protected Boolean autoMinorVersionUpgrade;
    @XmlElement(name = "LicenseModel")
    protected String licenseModel;
    @XmlElement(name = "Iops")
    protected BigInteger iops;
    @XmlElement(name = "OptionGroupName")
    protected String optionGroupName;
    @XmlElement(name = "CharacterSetName")
    protected String characterSetName;
    @XmlElement(name = "PubliclyAccessible")
    protected Boolean publiclyAccessible;
    @XmlElement(name = "Tags")
    protected TagList tags;
    @XmlElement(name = "StorageType")
    protected String storageType;
    @XmlElement(name = "TdeCredentialArn")
    protected String tdeCredentialArn;
    @XmlElement(name = "TdeCredentialPassword")
    protected String tdeCredentialPassword;

    /**
     * Gets the value of the dbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBName() {
        return dbName;
    }

    /**
     * Sets the value of the dbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBName(String value) {
        this.dbName = value;
    }

    /**
     * Gets the value of the dbInstanceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBInstanceIdentifier() {
        return dbInstanceIdentifier;
    }

    /**
     * Sets the value of the dbInstanceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBInstanceIdentifier(String value) {
        this.dbInstanceIdentifier = value;
    }

    /**
     * Gets the value of the allocatedStorage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllocatedStorage() {
        return allocatedStorage;
    }

    /**
     * Sets the value of the allocatedStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllocatedStorage(BigInteger value) {
        this.allocatedStorage = value;
    }

    /**
     * Gets the value of the dbInstanceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBInstanceClass() {
        return dbInstanceClass;
    }

    /**
     * Sets the value of the dbInstanceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBInstanceClass(String value) {
        this.dbInstanceClass = value;
    }

    /**
     * Gets the value of the engine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngine() {
        return engine;
    }

    /**
     * Sets the value of the engine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngine(String value) {
        this.engine = value;
    }

    /**
     * Gets the value of the masterUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterUsername() {
        return masterUsername;
    }

    /**
     * Sets the value of the masterUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterUsername(String value) {
        this.masterUsername = value;
    }

    /**
     * Gets the value of the masterUserPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterUserPassword() {
        return masterUserPassword;
    }

    /**
     * Sets the value of the masterUserPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterUserPassword(String value) {
        this.masterUserPassword = value;
    }

    /**
     * Gets the value of the dbSecurityGroups property.
     * 
     * @return
     *     possible object is
     *     {@link DBSecurityGroupNameList }
     *     
     */
    public DBSecurityGroupNameList getDBSecurityGroups() {
        return dbSecurityGroups;
    }

    /**
     * Sets the value of the dbSecurityGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBSecurityGroupNameList }
     *     
     */
    public void setDBSecurityGroups(DBSecurityGroupNameList value) {
        this.dbSecurityGroups = value;
    }

    /**
     * Gets the value of the vpcSecurityGroupIds property.
     * 
     * @return
     *     possible object is
     *     {@link VpcSecurityGroupIdList }
     *     
     */
    public VpcSecurityGroupIdList getVpcSecurityGroupIds() {
        return vpcSecurityGroupIds;
    }

    /**
     * Sets the value of the vpcSecurityGroupIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link VpcSecurityGroupIdList }
     *     
     */
    public void setVpcSecurityGroupIds(VpcSecurityGroupIdList value) {
        this.vpcSecurityGroupIds = value;
    }

    /**
     * Gets the value of the availabilityZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityZone() {
        return availabilityZone;
    }

    /**
     * Sets the value of the availabilityZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityZone(String value) {
        this.availabilityZone = value;
    }

    /**
     * Gets the value of the dbSubnetGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBSubnetGroupName() {
        return dbSubnetGroupName;
    }

    /**
     * Sets the value of the dbSubnetGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBSubnetGroupName(String value) {
        this.dbSubnetGroupName = value;
    }

    /**
     * Gets the value of the preferredMaintenanceWindow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredMaintenanceWindow() {
        return preferredMaintenanceWindow;
    }

    /**
     * Sets the value of the preferredMaintenanceWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredMaintenanceWindow(String value) {
        this.preferredMaintenanceWindow = value;
    }

    /**
     * Gets the value of the dbParameterGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBParameterGroupName() {
        return dbParameterGroupName;
    }

    /**
     * Sets the value of the dbParameterGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBParameterGroupName(String value) {
        this.dbParameterGroupName = value;
    }

    /**
     * Gets the value of the backupRetentionPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBackupRetentionPeriod() {
        return backupRetentionPeriod;
    }

    /**
     * Sets the value of the backupRetentionPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBackupRetentionPeriod(BigInteger value) {
        this.backupRetentionPeriod = value;
    }

    /**
     * Gets the value of the preferredBackupWindow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredBackupWindow() {
        return preferredBackupWindow;
    }

    /**
     * Sets the value of the preferredBackupWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredBackupWindow(String value) {
        this.preferredBackupWindow = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPort(BigInteger value) {
        this.port = value;
    }

    /**
     * Gets the value of the multiAZ property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getMultiAZ() {
        return multiAZ;
    }

    /**
     * Sets the value of the multiAZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiAZ(Boolean value) {
        this.multiAZ = value;
    }

    /**
     * Gets the value of the engineVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineVersion() {
        return engineVersion;
    }

    /**
     * Sets the value of the engineVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineVersion(String value) {
        this.engineVersion = value;
    }

    /**
     * Gets the value of the autoMinorVersionUpgrade property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAutoMinorVersionUpgrade() {
        return autoMinorVersionUpgrade;
    }

    /**
     * Sets the value of the autoMinorVersionUpgrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoMinorVersionUpgrade(Boolean value) {
        this.autoMinorVersionUpgrade = value;
    }

    /**
     * Gets the value of the licenseModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseModel() {
        return licenseModel;
    }

    /**
     * Sets the value of the licenseModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseModel(String value) {
        this.licenseModel = value;
    }

    /**
     * Gets the value of the iops property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIops() {
        return iops;
    }

    /**
     * Sets the value of the iops property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIops(BigInteger value) {
        this.iops = value;
    }

    /**
     * Gets the value of the optionGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionGroupName() {
        return optionGroupName;
    }

    /**
     * Sets the value of the optionGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionGroupName(String value) {
        this.optionGroupName = value;
    }

    /**
     * Gets the value of the characterSetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharacterSetName() {
        return characterSetName;
    }

    /**
     * Sets the value of the characterSetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharacterSetName(String value) {
        this.characterSetName = value;
    }

    /**
     * Gets the value of the publiclyAccessible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPubliclyAccessible() {
        return publiclyAccessible;
    }

    /**
     * Sets the value of the publiclyAccessible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPubliclyAccessible(Boolean value) {
        this.publiclyAccessible = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link TagList }
     *     
     */
    public TagList getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagList }
     *     
     */
    public void setTags(TagList value) {
        this.tags = value;
    }

    /**
     * Gets the value of the storageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageType() {
        return storageType;
    }

    /**
     * Sets the value of the storageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageType(String value) {
        this.storageType = value;
    }

    /**
     * Gets the value of the tdeCredentialArn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdeCredentialArn() {
        return tdeCredentialArn;
    }

    /**
     * Sets the value of the tdeCredentialArn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdeCredentialArn(String value) {
        this.tdeCredentialArn = value;
    }

    /**
     * Gets the value of the tdeCredentialPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdeCredentialPassword() {
        return tdeCredentialPassword;
    }

    /**
     * Sets the value of the tdeCredentialPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdeCredentialPassword(String value) {
        this.tdeCredentialPassword = value;
    }

}
