//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.17 at 01:23:02 PM CST 
//


package com.amazonaws.rds.doc._2010_07_28;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *                 <p>
 *                     Contains the result of a successful invocation of the following actions:
 *                 </p>
 *                 <ul>
 *                     <li><a>CreateDBInstance</a></li>
 *                     <li><a>DeleteDBInstance</a></li>
 *                     <li><a>ModifyDBInstance</a></li>
 *                 </ul>
 *                 <p>This data type is used as a response element in the <a>DescribeDBInstances</a> action.</p>
 *             
 * 
 * <p>Java class for DBInstance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DBInstance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBInstanceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DBInstanceClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Engine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DBInstanceStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MasterUsername" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DBName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Endpoint" type="{http://rds.amazonaws.com/doc/2014-09-01/}Endpoint" minOccurs="0"/>
 *         &lt;element name="AllocatedStorage" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="InstanceCreateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="PreferredBackupWindow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BackupRetentionPeriod" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="DBSecurityGroups" type="{http://rds.amazonaws.com/doc/2014-09-01/}DBSecurityGroupMembershipList" minOccurs="0"/>
 *         &lt;element name="VpcSecurityGroups" type="{http://rds.amazonaws.com/doc/2014-09-01/}VpcSecurityGroupMembershipList" minOccurs="0"/>
 *         &lt;element name="DBParameterGroups" type="{http://rds.amazonaws.com/doc/2014-09-01/}DBParameterGroupStatusList" minOccurs="0"/>
 *         &lt;element name="AvailabilityZone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DBSubnetGroup" type="{http://rds.amazonaws.com/doc/2014-09-01/}DBSubnetGroup" minOccurs="0"/>
 *         &lt;element name="PreferredMaintenanceWindow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PendingModifiedValues" type="{http://rds.amazonaws.com/doc/2014-09-01/}PendingModifiedValues" minOccurs="0"/>
 *         &lt;element name="LatestRestorableTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="MultiAZ" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EngineVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoMinorVersionUpgrade" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ReadReplicaSourceDBInstanceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReadReplicaDBInstanceIdentifiers" type="{http://rds.amazonaws.com/doc/2014-09-01/}ReadReplicaDBInstanceIdentifierList" minOccurs="0"/>
 *         &lt;element name="LicenseModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Iops" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="OptionGroupMemberships" type="{http://rds.amazonaws.com/doc/2014-09-01/}OptionGroupMembershipList" minOccurs="0"/>
 *         &lt;element name="CharacterSetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SecondaryAvailabilityZone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PubliclyAccessible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="StatusInfos" type="{http://rds.amazonaws.com/doc/2014-09-01/}DBInstanceStatusInfoList" minOccurs="0"/>
 *         &lt;element name="StorageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TdeCredentialArn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DBInstance", propOrder = {
    "dbInstanceIdentifier",
    "dbInstanceClass",
    "engine",
    "dbInstanceStatus",
    "masterUsername",
    "dbName",
    "endpoint",
    "allocatedStorage",
    "instanceCreateTime",
    "preferredBackupWindow",
    "backupRetentionPeriod",
    "dbSecurityGroups",
    "vpcSecurityGroups",
    "dbParameterGroups",
    "availabilityZone",
    "dbSubnetGroup",
    "preferredMaintenanceWindow",
    "pendingModifiedValues",
    "latestRestorableTime",
    "multiAZ",
    "engineVersion",
    "autoMinorVersionUpgrade",
    "readReplicaSourceDBInstanceIdentifier",
    "readReplicaDBInstanceIdentifiers",
    "licenseModel",
    "iops",
    "optionGroupMemberships",
    "characterSetName",
    "secondaryAvailabilityZone",
    "publiclyAccessible",
    "statusInfos",
    "storageType",
    "tdeCredentialArn"
})
public class DBInstance {

    @XmlElement(name = "DBInstanceIdentifier")
    protected String dbInstanceIdentifier;
    @XmlElement(name = "DBInstanceClass")
    protected String dbInstanceClass;
    @XmlElement(name = "Engine")
    protected String engine;
    @XmlElement(name = "DBInstanceStatus")
    protected String dbInstanceStatus;
    @XmlElement(name = "MasterUsername")
    protected String masterUsername;
    @XmlElement(name = "DBName")
    protected String dbName;
    @XmlElement(name = "Endpoint")
    protected Endpoint endpoint;
    @XmlElement(name = "AllocatedStorage")
    protected BigInteger allocatedStorage;
    @XmlElement(name = "InstanceCreateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar instanceCreateTime;
    @XmlElement(name = "PreferredBackupWindow")
    protected String preferredBackupWindow;
    @XmlElement(name = "BackupRetentionPeriod")
    protected BigInteger backupRetentionPeriod;
    @XmlElement(name = "DBSecurityGroups")
    protected DBSecurityGroupMembershipList dbSecurityGroups;
    @XmlElement(name = "VpcSecurityGroups")
    protected VpcSecurityGroupMembershipList vpcSecurityGroups;
    @XmlElement(name = "DBParameterGroups")
    protected DBParameterGroupStatusList dbParameterGroups;
    @XmlElement(name = "AvailabilityZone")
    protected String availabilityZone;
    @XmlElement(name = "DBSubnetGroup")
    protected DBSubnetGroup dbSubnetGroup;
    @XmlElement(name = "PreferredMaintenanceWindow")
    protected String preferredMaintenanceWindow;
    @XmlElement(name = "PendingModifiedValues")
    protected PendingModifiedValues pendingModifiedValues;
    @XmlElement(name = "LatestRestorableTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar latestRestorableTime;
    @XmlElement(name = "MultiAZ")
    protected Boolean multiAZ;
    @XmlElement(name = "EngineVersion")
    protected String engineVersion;
    @XmlElement(name = "AutoMinorVersionUpgrade")
    protected Boolean autoMinorVersionUpgrade;
    @XmlElement(name = "ReadReplicaSourceDBInstanceIdentifier")
    protected String readReplicaSourceDBInstanceIdentifier;
    @XmlElement(name = "ReadReplicaDBInstanceIdentifiers")
    protected ReadReplicaDBInstanceIdentifierList readReplicaDBInstanceIdentifiers;
    @XmlElement(name = "LicenseModel")
    protected String licenseModel;
    @XmlElement(name = "Iops")
    protected BigInteger iops;
    @XmlElement(name = "OptionGroupMemberships")
    protected OptionGroupMembershipList optionGroupMemberships;
    @XmlElement(name = "CharacterSetName")
    protected String characterSetName;
    @XmlElement(name = "SecondaryAvailabilityZone")
    protected String secondaryAvailabilityZone;
    @XmlElement(name = "PubliclyAccessible")
    protected Boolean publiclyAccessible;
    @XmlElement(name = "StatusInfos")
    protected DBInstanceStatusInfoList statusInfos;
    @XmlElement(name = "StorageType")
    protected String storageType;
    @XmlElement(name = "TdeCredentialArn")
    protected String tdeCredentialArn;

    /**
     * Gets the value of the dbInstanceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBInstanceIdentifier() {
        return dbInstanceIdentifier;
    }

    /**
     * Sets the value of the dbInstanceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBInstanceIdentifier(String value) {
        this.dbInstanceIdentifier = value;
    }

    /**
     * Gets the value of the dbInstanceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBInstanceClass() {
        return dbInstanceClass;
    }

    /**
     * Sets the value of the dbInstanceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBInstanceClass(String value) {
        this.dbInstanceClass = value;
    }

    /**
     * Gets the value of the engine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngine() {
        return engine;
    }

    /**
     * Sets the value of the engine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngine(String value) {
        this.engine = value;
    }

    /**
     * Gets the value of the dbInstanceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBInstanceStatus() {
        return dbInstanceStatus;
    }

    /**
     * Sets the value of the dbInstanceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBInstanceStatus(String value) {
        this.dbInstanceStatus = value;
    }

    /**
     * Gets the value of the masterUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterUsername() {
        return masterUsername;
    }

    /**
     * Sets the value of the masterUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterUsername(String value) {
        this.masterUsername = value;
    }

    /**
     * Gets the value of the dbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBName() {
        return dbName;
    }

    /**
     * Sets the value of the dbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBName(String value) {
        this.dbName = value;
    }

    /**
     * Gets the value of the endpoint property.
     * 
     * @return
     *     possible object is
     *     {@link Endpoint }
     *     
     */
    public Endpoint getEndpoint() {
        return endpoint;
    }

    /**
     * Sets the value of the endpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Endpoint }
     *     
     */
    public void setEndpoint(Endpoint value) {
        this.endpoint = value;
    }

    /**
     * Gets the value of the allocatedStorage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllocatedStorage() {
        return allocatedStorage;
    }

    /**
     * Sets the value of the allocatedStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllocatedStorage(BigInteger value) {
        this.allocatedStorage = value;
    }

    /**
     * Gets the value of the instanceCreateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInstanceCreateTime() {
        return instanceCreateTime;
    }

    /**
     * Sets the value of the instanceCreateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInstanceCreateTime(XMLGregorianCalendar value) {
        this.instanceCreateTime = value;
    }

    /**
     * Gets the value of the preferredBackupWindow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredBackupWindow() {
        return preferredBackupWindow;
    }

    /**
     * Sets the value of the preferredBackupWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredBackupWindow(String value) {
        this.preferredBackupWindow = value;
    }

    /**
     * Gets the value of the backupRetentionPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBackupRetentionPeriod() {
        return backupRetentionPeriod;
    }

    /**
     * Sets the value of the backupRetentionPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBackupRetentionPeriod(BigInteger value) {
        this.backupRetentionPeriod = value;
    }

    /**
     * Gets the value of the dbSecurityGroups property.
     * 
     * @return
     *     possible object is
     *     {@link DBSecurityGroupMembershipList }
     *     
     */
    public DBSecurityGroupMembershipList getDBSecurityGroups() {
        return dbSecurityGroups;
    }

    /**
     * Sets the value of the dbSecurityGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBSecurityGroupMembershipList }
     *     
     */
    public void setDBSecurityGroups(DBSecurityGroupMembershipList value) {
        this.dbSecurityGroups = value;
    }

    /**
     * Gets the value of the vpcSecurityGroups property.
     * 
     * @return
     *     possible object is
     *     {@link VpcSecurityGroupMembershipList }
     *     
     */
    public VpcSecurityGroupMembershipList getVpcSecurityGroups() {
        return vpcSecurityGroups;
    }

    /**
     * Sets the value of the vpcSecurityGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link VpcSecurityGroupMembershipList }
     *     
     */
    public void setVpcSecurityGroups(VpcSecurityGroupMembershipList value) {
        this.vpcSecurityGroups = value;
    }

    /**
     * Gets the value of the dbParameterGroups property.
     * 
     * @return
     *     possible object is
     *     {@link DBParameterGroupStatusList }
     *     
     */
    public DBParameterGroupStatusList getDBParameterGroups() {
        return dbParameterGroups;
    }

    /**
     * Sets the value of the dbParameterGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBParameterGroupStatusList }
     *     
     */
    public void setDBParameterGroups(DBParameterGroupStatusList value) {
        this.dbParameterGroups = value;
    }

    /**
     * Gets the value of the availabilityZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityZone() {
        return availabilityZone;
    }

    /**
     * Sets the value of the availabilityZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityZone(String value) {
        this.availabilityZone = value;
    }

    /**
     * Gets the value of the dbSubnetGroup property.
     * 
     * @return
     *     possible object is
     *     {@link DBSubnetGroup }
     *     
     */
    public DBSubnetGroup getDBSubnetGroup() {
        return dbSubnetGroup;
    }

    /**
     * Sets the value of the dbSubnetGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBSubnetGroup }
     *     
     */
    public void setDBSubnetGroup(DBSubnetGroup value) {
        this.dbSubnetGroup = value;
    }

    /**
     * Gets the value of the preferredMaintenanceWindow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredMaintenanceWindow() {
        return preferredMaintenanceWindow;
    }

    /**
     * Sets the value of the preferredMaintenanceWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredMaintenanceWindow(String value) {
        this.preferredMaintenanceWindow = value;
    }

    /**
     * Gets the value of the pendingModifiedValues property.
     * 
     * @return
     *     possible object is
     *     {@link PendingModifiedValues }
     *     
     */
    public PendingModifiedValues getPendingModifiedValues() {
        return pendingModifiedValues;
    }

    /**
     * Sets the value of the pendingModifiedValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link PendingModifiedValues }
     *     
     */
    public void setPendingModifiedValues(PendingModifiedValues value) {
        this.pendingModifiedValues = value;
    }

    /**
     * Gets the value of the latestRestorableTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLatestRestorableTime() {
        return latestRestorableTime;
    }

    /**
     * Sets the value of the latestRestorableTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLatestRestorableTime(XMLGregorianCalendar value) {
        this.latestRestorableTime = value;
    }

    /**
     * Gets the value of the multiAZ property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getMultiAZ() {
        return multiAZ;
    }

    /**
     * Sets the value of the multiAZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiAZ(Boolean value) {
        this.multiAZ = value;
    }

    /**
     * Gets the value of the engineVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineVersion() {
        return engineVersion;
    }

    /**
     * Sets the value of the engineVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineVersion(String value) {
        this.engineVersion = value;
    }

    /**
     * Gets the value of the autoMinorVersionUpgrade property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAutoMinorVersionUpgrade() {
        return autoMinorVersionUpgrade;
    }

    /**
     * Sets the value of the autoMinorVersionUpgrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoMinorVersionUpgrade(Boolean value) {
        this.autoMinorVersionUpgrade = value;
    }

    /**
     * Gets the value of the readReplicaSourceDBInstanceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadReplicaSourceDBInstanceIdentifier() {
        return readReplicaSourceDBInstanceIdentifier;
    }

    /**
     * Sets the value of the readReplicaSourceDBInstanceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadReplicaSourceDBInstanceIdentifier(String value) {
        this.readReplicaSourceDBInstanceIdentifier = value;
    }

    /**
     * Gets the value of the readReplicaDBInstanceIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link ReadReplicaDBInstanceIdentifierList }
     *     
     */
    public ReadReplicaDBInstanceIdentifierList getReadReplicaDBInstanceIdentifiers() {
        return readReplicaDBInstanceIdentifiers;
    }

    /**
     * Sets the value of the readReplicaDBInstanceIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadReplicaDBInstanceIdentifierList }
     *     
     */
    public void setReadReplicaDBInstanceIdentifiers(ReadReplicaDBInstanceIdentifierList value) {
        this.readReplicaDBInstanceIdentifiers = value;
    }

    /**
     * Gets the value of the licenseModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseModel() {
        return licenseModel;
    }

    /**
     * Sets the value of the licenseModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseModel(String value) {
        this.licenseModel = value;
    }

    /**
     * Gets the value of the iops property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIops() {
        return iops;
    }

    /**
     * Sets the value of the iops property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIops(BigInteger value) {
        this.iops = value;
    }

    /**
     * Gets the value of the optionGroupMemberships property.
     * 
     * @return
     *     possible object is
     *     {@link OptionGroupMembershipList }
     *     
     */
    public OptionGroupMembershipList getOptionGroupMemberships() {
        return optionGroupMemberships;
    }

    /**
     * Sets the value of the optionGroupMemberships property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionGroupMembershipList }
     *     
     */
    public void setOptionGroupMemberships(OptionGroupMembershipList value) {
        this.optionGroupMemberships = value;
    }

    /**
     * Gets the value of the characterSetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharacterSetName() {
        return characterSetName;
    }

    /**
     * Sets the value of the characterSetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharacterSetName(String value) {
        this.characterSetName = value;
    }

    /**
     * Gets the value of the secondaryAvailabilityZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryAvailabilityZone() {
        return secondaryAvailabilityZone;
    }

    /**
     * Sets the value of the secondaryAvailabilityZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryAvailabilityZone(String value) {
        this.secondaryAvailabilityZone = value;
    }

    /**
     * Gets the value of the publiclyAccessible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPubliclyAccessible() {
        return publiclyAccessible;
    }

    /**
     * Sets the value of the publiclyAccessible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPubliclyAccessible(Boolean value) {
        this.publiclyAccessible = value;
    }

    /**
     * Gets the value of the statusInfos property.
     * 
     * @return
     *     possible object is
     *     {@link DBInstanceStatusInfoList }
     *     
     */
    public DBInstanceStatusInfoList getStatusInfos() {
        return statusInfos;
    }

    /**
     * Sets the value of the statusInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBInstanceStatusInfoList }
     *     
     */
    public void setStatusInfos(DBInstanceStatusInfoList value) {
        this.statusInfos = value;
    }

    /**
     * Gets the value of the storageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageType() {
        return storageType;
    }

    /**
     * Sets the value of the storageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageType(String value) {
        this.storageType = value;
    }

    /**
     * Gets the value of the tdeCredentialArn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdeCredentialArn() {
        return tdeCredentialArn;
    }

    /**
     * Sets the value of the tdeCredentialArn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdeCredentialArn(String value) {
        this.tdeCredentialArn = value;
    }

}
