//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.17 at 01:23:02 PM CST 
//


package com.amazonaws.rds.doc._2010_07_28;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 <p>
 *                     Contains the result of a successful invocation of the following actions:
 *                 </p>
 *                 <ul>
 *                     <li><a>CreateDBSubnetGroup</a></li>
 *                     <li><a>ModifyDBSubnetGroup</a></li>
 *                     <li><a>DescribeDBSubnetGroups</a></li>
 *                     <li><a>DeleteDBSubnetGroup</a></li>
 *                 </ul>
 *                 <p>This data type is used as a response element in the <a>DescribeDBSubnetGroups</a> action.</p>
 *             
 * 
 * <p>Java class for DBSubnetGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DBSubnetGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBSubnetGroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DBSubnetGroupDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VpcId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubnetGroupStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Subnets" type="{http://rds.amazonaws.com/doc/2014-09-01/}SubnetList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DBSubnetGroup", propOrder = {
    "dbSubnetGroupName",
    "dbSubnetGroupDescription",
    "vpcId",
    "subnetGroupStatus",
    "subnets"
})
public class DBSubnetGroup {

    @XmlElement(name = "DBSubnetGroupName")
    protected String dbSubnetGroupName;
    @XmlElement(name = "DBSubnetGroupDescription")
    protected String dbSubnetGroupDescription;
    @XmlElement(name = "VpcId")
    protected String vpcId;
    @XmlElement(name = "SubnetGroupStatus")
    protected String subnetGroupStatus;
    @XmlElement(name = "Subnets")
    protected SubnetList subnets;

    /**
     * Gets the value of the dbSubnetGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBSubnetGroupName() {
        return dbSubnetGroupName;
    }

    /**
     * Sets the value of the dbSubnetGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBSubnetGroupName(String value) {
        this.dbSubnetGroupName = value;
    }

    /**
     * Gets the value of the dbSubnetGroupDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBSubnetGroupDescription() {
        return dbSubnetGroupDescription;
    }

    /**
     * Sets the value of the dbSubnetGroupDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBSubnetGroupDescription(String value) {
        this.dbSubnetGroupDescription = value;
    }

    /**
     * Gets the value of the vpcId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVpcId() {
        return vpcId;
    }

    /**
     * Sets the value of the vpcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVpcId(String value) {
        this.vpcId = value;
    }

    /**
     * Gets the value of the subnetGroupStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubnetGroupStatus() {
        return subnetGroupStatus;
    }

    /**
     * Sets the value of the subnetGroupStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubnetGroupStatus(String value) {
        this.subnetGroupStatus = value;
    }

    /**
     * Gets the value of the subnets property.
     * 
     * @return
     *     possible object is
     *     {@link SubnetList }
     *     
     */
    public SubnetList getSubnets() {
        return subnets;
    }

    /**
     * Sets the value of the subnets property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubnetList }
     *     
     */
    public void setSubnets(SubnetList value) {
        this.subnets = value;
    }

}
