//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.17 at 01:23:02 PM CST 
//


package com.amazonaws.rds.doc._2010_07_28;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                     <p>
 *                         Contains the result of a successful invocation of the following actions:
 *                     </p>
 *                     <ul>
 *                         <li><a>CreateDBInstance</a></li>
 *                         <li><a>DeleteDBInstance</a></li>
 *                         <li><a>ModifyDBInstance</a></li>
 *                     </ul>
 *                     <p>This data type is used as a response element in the <a>DescribeDBInstances</a> action.</p>
 *                 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBInstance" type="{http://rds.amazonaws.com/doc/2014-09-01/}DBInstance"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbInstance"
})
@XmlRootElement(name = "DeleteDBInstanceResult")
public class DeleteDBInstanceResult {

    @XmlElement(name = "DBInstance", required = true)
    protected DBInstance dbInstance;

    /**
     * Gets the value of the dbInstance property.
     * 
     * @return
     *     possible object is
     *     {@link DBInstance }
     *     
     */
    public DBInstance getDBInstance() {
        return dbInstance;
    }

    /**
     * Sets the value of the dbInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBInstance }
     *     
     */
    public void setDBInstance(DBInstance value) {
        this.dbInstance = value;
    }

}
