//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.01 at 08:18:37 AM CDT 
//


package com.amazonaws.rds.doc._2010_07_28;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://rds.amazonaws.com/doc/2010-07-28/}DescribeDBParametersResult"/>
 *         &lt;element ref="{http://rds.amazonaws.com/doc/2010-07-28/}ResponseMetadata"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "describeDBParametersResult",
    "responseMetadata"
})
@XmlRootElement(name = "DescribeDBParametersResponse")
public class DescribeDBParametersResponse {

    @XmlElement(name = "DescribeDBParametersResult", required = true)
    protected DescribeDBParametersResult describeDBParametersResult;
    @XmlElement(name = "ResponseMetadata", required = true)
    protected ResponseMetadata responseMetadata;

    /**
     * Gets the value of the describeDBParametersResult property.
     * 
     * @return
     *     possible object is
     *     {@link DescribeDBParametersResult }
     *     
     */
    public DescribeDBParametersResult getDescribeDBParametersResult() {
        return describeDBParametersResult;
    }

    /**
     * Sets the value of the describeDBParametersResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescribeDBParametersResult }
     *     
     */
    public void setDescribeDBParametersResult(DescribeDBParametersResult value) {
        this.describeDBParametersResult = value;
    }

    /**
     * Gets the value of the responseMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMetadata }
     *     
     */
    public ResponseMetadata getResponseMetadata() {
        return responseMetadata;
    }

    /**
     * Sets the value of the responseMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMetadata }
     *     
     */
    public void setResponseMetadata(ResponseMetadata value) {
        this.responseMetadata = value;
    }

}
