//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.01 at 08:18:37 AM CDT 
//


package com.amazonaws.rds.doc._2010_07_28;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amazonaws.rds.doc._2010_07_28 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amazonaws.rds.doc._2010_07_28
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModifyDBParameterGroupResponse }
     * 
     */
    public ModifyDBParameterGroupResponse createModifyDBParameterGroupResponse() {
        return new ModifyDBParameterGroupResponse();
    }

    /**
     * Create an instance of {@link ModifyDBParameterGroupResult }
     * 
     */
    public ModifyDBParameterGroupResult createModifyDBParameterGroupResult() {
        return new ModifyDBParameterGroupResult();
    }

    /**
     * Create an instance of {@link ResponseMetadata }
     * 
     */
    public ResponseMetadata createResponseMetadata() {
        return new ResponseMetadata();
    }

    /**
     * Create an instance of {@link CreateDBParameterGroup }
     * 
     */
    public CreateDBParameterGroup createCreateDBParameterGroup() {
        return new CreateDBParameterGroup();
    }

    /**
     * Create an instance of {@link DeleteDBParameterGroupResponse }
     * 
     */
    public DeleteDBParameterGroupResponse createDeleteDBParameterGroupResponse() {
        return new DeleteDBParameterGroupResponse();
    }

    /**
     * Create an instance of {@link CreateDBParameterGroupResult }
     * 
     */
    public CreateDBParameterGroupResult createCreateDBParameterGroupResult() {
        return new CreateDBParameterGroupResult();
    }

    /**
     * Create an instance of {@link DBParameterGroup }
     * 
     */
    public DBParameterGroup createDBParameterGroup() {
        return new DBParameterGroup();
    }

    /**
     * Create an instance of {@link DeleteDBParameterGroup }
     * 
     */
    public DeleteDBParameterGroup createDeleteDBParameterGroup() {
        return new DeleteDBParameterGroup();
    }

    /**
     * Create an instance of {@link ModifyDBParameterGroup }
     * 
     */
    public ModifyDBParameterGroup createModifyDBParameterGroup() {
        return new ModifyDBParameterGroup();
    }

    /**
     * Create an instance of {@link ParametersList }
     * 
     */
    public ParametersList createParametersList() {
        return new ParametersList();
    }

    /**
     * Create an instance of {@link DescribeDBParametersResult }
     * 
     */
    public DescribeDBParametersResult createDescribeDBParametersResult() {
        return new DescribeDBParametersResult();
    }

    /**
     * Create an instance of {@link DescribeDBParametersResponse }
     * 
     */
    public DescribeDBParametersResponse createDescribeDBParametersResponse() {
        return new DescribeDBParametersResponse();
    }

    /**
     * Create an instance of {@link CreateDBParameterGroupResponse }
     * 
     */
    public CreateDBParameterGroupResponse createCreateDBParameterGroupResponse() {
        return new CreateDBParameterGroupResponse();
    }

    /**
     * Create an instance of {@link DescribeDBParameters }
     * 
     */
    public DescribeDBParameters createDescribeDBParameters() {
        return new DescribeDBParameters();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    public CreateDBInstanceResponse createCreateDBInstanceResponse() {
        return new CreateDBInstanceResponse();
    }
    public CreateDBInstance createCreateDBInstance() {
        return new CreateDBInstance();
    }
    public DeleteDBInstanceResult createDeleteDBInstanceResult() {
        return new DeleteDBInstanceResult();
    }
    public DeleteDBInstanceResponse createDeleteDBInstanceResponse() {
        return new DeleteDBInstanceResponse();
    }
    public DeleteDBInstance createDeleteDBInstance() {
        return new DeleteDBInstance();
    }
    public CreateDBInstanceResult createCreateDBInstanceResult() {
        return new CreateDBInstanceResult();
    }
    public DBInstanceStatusInfoList createDBInstanceStatusInfoList() {
        return new DBInstanceStatusInfoList();
    }
    public DBInstanceStatusInfo createDBInstanceStatusInfo() {
        return new DBInstanceStatusInfo();
    }
    public DBInstanceList createDBInstanceList() {
        return new DBInstanceList();
    }
    public DBInstance createDBInstance() {
        return new DBInstance();
    }
    public DBSecurityGroupNameList createDBSecurityGroupNameList() {
        return new DBSecurityGroupNameList();
    }
    public DBSubnetGroup createDBSubnetGroup() {
        return new DBSubnetGroup();
    }
    public Endpoint createEndpoint() {
        return new Endpoint();
    }
    public OptionGroupMembership createOptionGroupMembership() {
        return new OptionGroupMembership();
    }
    public OptionGroupMembershipList createOptionGroupMembershipList() {
        return new OptionGroupMembershipList();
    }
    public Subnet createSubnet() {
        return new Subnet();
    }
    public SubnetList createSubnetList() {
        return new SubnetList();
    }
    public Tag createTag() {
        return new Tag();
    }
    public TagList createTagList() {
        return new TagList();
    }

    public AvailabilityZone createAvailabilityZone() {
        return new AvailabilityZone();
    }
    public DBParameterGroupStatus createDBParameterGroupStatus() {
        return new DBParameterGroupStatus();
    }
    public DBParameterGroupStatusList createDBParameterGroupStatusList() {
        return new DBParameterGroupStatusList();
    }
    public DBSecurityGroupMembership createDBSecurityGroupMembership() {
        return new DBSecurityGroupMembership();
    }
    public DBSecurityGroupMembershipList createDBSecurityGroupMembershipList() {
        return new DBSecurityGroupMembershipList();
    }
    public ReadReplicaDBInstanceIdentifierList createReadReplicaDBInstanceIdentifierList() {
        return new ReadReplicaDBInstanceIdentifierList();
    }
    public VpcSecurityGroupIdList createVpcSecurityGroupIdList() {
        return new VpcSecurityGroupIdList();
    }
    public VpcSecurityGroupMembership createVpcSecurityGroupMembership() {
        return new VpcSecurityGroupMembership();
    }
    public VpcSecurityGroupMembershipList createVpcSecurityGroupMembershipList() {
        return new VpcSecurityGroupMembershipList();
    }
}
