//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.17 at 01:23:02 PM CST 
//


package com.amazonaws.rds.doc._2010_07_28;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 <p>
 *                 This data type is used as a response element in the <a>DescribeDBSubnetGroups</a> action.
 *                 </p>
 *             
 * 
 * <p>Java class for Subnet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Subnet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubnetIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubnetAvailabilityZone" type="{http://rds.amazonaws.com/doc/2014-09-01/}AvailabilityZone" minOccurs="0"/>
 *         &lt;element name="SubnetStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Subnet", propOrder = {
    "subnetIdentifier",
    "subnetAvailabilityZone",
    "subnetStatus"
})
public class Subnet {

    @XmlElement(name = "SubnetIdentifier")
    protected String subnetIdentifier;
    @XmlElement(name = "SubnetAvailabilityZone")
    protected AvailabilityZone subnetAvailabilityZone;
    @XmlElement(name = "SubnetStatus")
    protected String subnetStatus;

    /**
     * Gets the value of the subnetIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubnetIdentifier() {
        return subnetIdentifier;
    }

    /**
     * Sets the value of the subnetIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubnetIdentifier(String value) {
        this.subnetIdentifier = value;
    }

    /**
     * Gets the value of the subnetAvailabilityZone property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityZone }
     *     
     */
    public AvailabilityZone getSubnetAvailabilityZone() {
        return subnetAvailabilityZone;
    }

    /**
     * Sets the value of the subnetAvailabilityZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityZone }
     *     
     */
    public void setSubnetAvailabilityZone(AvailabilityZone value) {
        this.subnetAvailabilityZone = value;
    }

    /**
     * Gets the value of the subnetStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubnetStatus() {
        return subnetStatus;
    }

    /**
     * Sets the value of the subnetStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubnetStatus(String value) {
        this.subnetStatus = value;
    }

}
