//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.23 at 03:48:19 PM CDT 
//


package com.amazonaws.cloudfront.doc._2015_07_27;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActiveTrustedSignersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActiveTrustedSignersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Enabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Items">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Signer">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AwsAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="KeyPairIds">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Items" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}KeyPairIdsItems"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActiveTrustedSignersType", propOrder = {
    "enabled",
    "quantity",
    "items"
})
public class ActiveTrustedSigners
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Enabled", required = true)
    protected String enabled;
    @XmlElement(name = "Quantity", required = true)
    protected String quantity;
    @XmlElement(name = "Items", required = true)
    protected ActiveTrustedSigners.Items items;

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnabled(String value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantity(String value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveTrustedSigners.Items }
     *     
     */
    public ActiveTrustedSigners.Items getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveTrustedSigners.Items }
     *     
     */
    public void setItems(ActiveTrustedSigners.Items value) {
        this.items = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Signer">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AwsAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="KeyPairIds">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Items" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}KeyPairIdsItems"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "signer"
    })
    public static class Items
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "Signer", required = true)
        protected ActiveTrustedSigners.Items.Signer signer;

        /**
         * Gets the value of the signer property.
         * 
         * @return
         *     possible object is
         *     {@link ActiveTrustedSigners.Items.Signer }
         *     
         */
        public ActiveTrustedSigners.Items.Signer getSigner() {
            return signer;
        }

        /**
         * Sets the value of the signer property.
         * 
         * @param value
         *     allowed object is
         *     {@link ActiveTrustedSigners.Items.Signer }
         *     
         */
        public void setSigner(ActiveTrustedSigners.Items.Signer value) {
            this.signer = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AwsAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="KeyPairIds">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Items" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}KeyPairIdsItems"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "awsAccountNumber",
            "keyPairIds"
        })
        public static class Signer
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "AwsAccountNumber", required = true)
            protected String awsAccountNumber;
            @XmlElement(name = "KeyPairIds", required = true)
            protected ActiveTrustedSigners.Items.Signer.KeyPairIds keyPairIds;

            /**
             * Gets the value of the awsAccountNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAwsAccountNumber() {
                return awsAccountNumber;
            }

            /**
             * Sets the value of the awsAccountNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAwsAccountNumber(String value) {
                this.awsAccountNumber = value;
            }

            /**
             * Gets the value of the keyPairIds property.
             * 
             * @return
             *     possible object is
             *     {@link ActiveTrustedSigners.Items.Signer.KeyPairIds }
             *     
             */
            public ActiveTrustedSigners.Items.Signer.KeyPairIds getKeyPairIds() {
                return keyPairIds;
            }

            /**
             * Sets the value of the keyPairIds property.
             * 
             * @param value
             *     allowed object is
             *     {@link ActiveTrustedSigners.Items.Signer.KeyPairIds }
             *     
             */
            public void setKeyPairIds(ActiveTrustedSigners.Items.Signer.KeyPairIds value) {
                this.keyPairIds = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Items" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}KeyPairIdsItems"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "quantity",
                "items"
            })
            public static class KeyPairIds
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(name = "Quantity", required = true)
                protected String quantity;
                @XmlElement(name = "Items", required = true)
                protected com.amazonaws.cloudfront.doc._2015_07_27.Items items;

                /**
                 * Gets the value of the quantity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getQuantity() {
                    return quantity;
                }

                /**
                 * Sets the value of the quantity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setQuantity(String value) {
                    this.quantity = value;
                }

                /**
                 * Gets the value of the items property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link com.amazonaws.cloudfront.doc._2015_07_27.Items }
                 *     
                 */
                public com.amazonaws.cloudfront.doc._2015_07_27.Items getItems() {
                    return items;
                }

                /**
                 * Sets the value of the items property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link com.amazonaws.cloudfront.doc._2015_07_27.Items }
                 *     
                 */
                public void setItems(com.amazonaws.cloudfront.doc._2015_07_27.Items value) {
                    this.items = value;
                }

            }

        }

    }

}
