//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.23 at 03:48:19 PM CDT 
//


package com.amazonaws.cloudfront.doc._2015_07_27;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DefaultCacheBehaviorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DefaultCacheBehaviorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TargetOriginId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ForwardedValues" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}ForwardedValuesType"/>
 *         &lt;element name="TrustedSigners" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}TrustedSignersType"/>
 *         &lt;element name="ViewerProtocolPolicy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MinTTL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AllowedMethods" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}AllowedMethodsType"/>
 *         &lt;element name="SmoothStreaming" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DefaultTTL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaxTTL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefaultCacheBehaviorType", propOrder = {
    "targetOriginId",
    "forwardedValues",
    "trustedSigners",
    "viewerProtocolPolicy",
    "minTTL",
    "allowedMethods",
    "smoothStreaming",
    "defaultTTL",
    "maxTTL"
})
public class DefaultCacheBehavior
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TargetOriginId", required = true)
    protected String targetOriginId;
    @XmlElement(name = "ForwardedValues", required = true)
    protected ForwardedValues forwardedValues;
    @XmlElement(name = "TrustedSigners", required = true)
    protected TrustedSigners trustedSigners;
    @XmlElement(name = "ViewerProtocolPolicy", required = true)
    protected String viewerProtocolPolicy;
    @XmlElement(name = "MinTTL", required = true)
    protected String minTTL;
    @XmlElement(name = "AllowedMethods", required = true)
    protected AllowedMethods allowedMethods;
    @XmlElement(name = "SmoothStreaming", required = true)
    protected String smoothStreaming;
    @XmlElement(name = "DefaultTTL", required = true)
    protected String defaultTTL;
    @XmlElement(name = "MaxTTL", required = true)
    protected String maxTTL;

    /**
     * Gets the value of the targetOriginId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetOriginId() {
        return targetOriginId;
    }

    /**
     * Sets the value of the targetOriginId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetOriginId(String value) {
        this.targetOriginId = value;
    }

    /**
     * Gets the value of the forwardedValues property.
     * 
     * @return
     *     possible object is
     *     {@link ForwardedValues }
     *     
     */
    public ForwardedValues getForwardedValues() {
        return forwardedValues;
    }

    /**
     * Sets the value of the forwardedValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForwardedValues }
     *     
     */
    public void setForwardedValues(ForwardedValues value) {
        this.forwardedValues = value;
    }

    /**
     * Gets the value of the trustedSigners property.
     * 
     * @return
     *     possible object is
     *     {@link TrustedSigners }
     *     
     */
    public TrustedSigners getTrustedSigners() {
        return trustedSigners;
    }

    /**
     * Sets the value of the trustedSigners property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrustedSigners }
     *     
     */
    public void setTrustedSigners(TrustedSigners value) {
        this.trustedSigners = value;
    }

    /**
     * Gets the value of the viewerProtocolPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewerProtocolPolicy() {
        return viewerProtocolPolicy;
    }

    /**
     * Sets the value of the viewerProtocolPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewerProtocolPolicy(String value) {
        this.viewerProtocolPolicy = value;
    }

    /**
     * Gets the value of the minTTL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinTTL() {
        return minTTL;
    }

    /**
     * Sets the value of the minTTL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinTTL(String value) {
        this.minTTL = value;
    }

    /**
     * Gets the value of the allowedMethods property.
     * 
     * @return
     *     possible object is
     *     {@link AllowedMethods }
     *     
     */
    public AllowedMethods getAllowedMethods() {
        return allowedMethods;
    }

    /**
     * Sets the value of the allowedMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllowedMethods }
     *     
     */
    public void setAllowedMethods(AllowedMethods value) {
        this.allowedMethods = value;
    }

    /**
     * Gets the value of the smoothStreaming property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmoothStreaming() {
        return smoothStreaming;
    }

    /**
     * Sets the value of the smoothStreaming property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmoothStreaming(String value) {
        this.smoothStreaming = value;
    }

    /**
     * Gets the value of the defaultTTL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultTTL() {
        return defaultTTL;
    }

    /**
     * Sets the value of the defaultTTL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultTTL(String value) {
        this.defaultTTL = value;
    }

    /**
     * Gets the value of the maxTTL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxTTL() {
        return maxTTL;
    }

    /**
     * Sets the value of the maxTTL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxTTL(String value) {
        this.maxTTL = value;
    }

}
