//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.23 at 03:48:19 PM CDT 
//


package com.amazonaws.cloudfront.doc._2015_07_27;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * <p>Java class for DistributionConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistributionConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CallerReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Aliases" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}AliasesType"/>
 *         &lt;element name="DefaultRootObject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Origins" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}OriginsType"/>
 *         &lt;element name="DefaultCacheBehavior" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}DefaultCacheBehaviorType"/>
 *         &lt;element name="CacheBehaviors" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}CacheBehaviorsType"/>
 *         &lt;element name="CustomErrorResponses" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}CustomErrorResponsesType"/>
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Logging" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}LoggingType"/>
 *         &lt;element name="PriceClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Enabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ViewerCertificate" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}ViewerCertificateType"/>
 *         &lt;element name="Restrictions" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}RestrictionsType"/>
 *         &lt;element name="WebACLId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributionConfigType", propOrder = {
    "callerReference",
    "aliases",
    "defaultRootObject",
    "origins",
    "defaultCacheBehavior",
    "cacheBehaviors",
    "customErrorResponses",
    "comment",
    "logging",
    "priceClass",
    "enabled",
    "viewerCertificate",
    "restrictions",
    "webACLId"
})
@XmlRootElement(name = "DistributionConfig")
public class DistributionConfig
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CallerReference", required = true)
    protected String callerReference;
    @XmlElement(name = "Aliases", required = true)
    protected Aliases aliases;
    @XmlElement(name = "DefaultRootObject", required = true)
    protected String defaultRootObject;
    @XmlElement(name = "Origins", required = true)
    protected Origins origins;
    @XmlElement(name = "DefaultCacheBehavior", required = true)
    protected DefaultCacheBehavior defaultCacheBehavior;
    @XmlElement(name = "CacheBehaviors", required = true)
    protected CacheBehaviors cacheBehaviors;
    @XmlElement(name = "CustomErrorResponses", required = true)
    protected CustomErrorResponses customErrorResponses;
    @XmlElement(name = "Comment", required = true)
    protected String comment;
    @XmlElement(name = "Logging", required = true)
    protected Logging logging;
    @XmlElement(name = "PriceClass", required = true)
    protected String priceClass;
    @XmlElement(name = "Enabled", required = true)
    protected String enabled;
    @XmlElement(name = "ViewerCertificate", required = true)
    protected ViewerCertificate viewerCertificate;
    @XmlElement(name = "Restrictions", required = true)
    protected Restrictions restrictions;
    @XmlElement(name = "WebACLId", required = true)
    protected String webACLId;

    /**
     * Gets the value of the callerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallerReference() {
        return callerReference;
    }

    /**
     * Sets the value of the callerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallerReference(String value) {
        this.callerReference = value;
    }

    /**
     * Gets the value of the aliases property.
     * 
     * @return
     *     possible object is
     *     {@link Aliases }
     *     
     */
    public Aliases getAliases() {
        return aliases;
    }

    /**
     * Sets the value of the aliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aliases }
     *     
     */
    public void setAliases(Aliases value) {
        this.aliases = value;
    }

    /**
     * Gets the value of the defaultRootObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultRootObject() {
        return defaultRootObject;
    }

    /**
     * Sets the value of the defaultRootObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultRootObject(String value) {
        this.defaultRootObject = value;
    }

    /**
     * Gets the value of the origins property.
     * 
     * @return
     *     possible object is
     *     {@link Origins }
     *     
     */
    public Origins getOrigins() {
        return origins;
    }

    /**
     * Sets the value of the origins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Origins }
     *     
     */
    public void setOrigins(Origins value) {
        this.origins = value;
    }

    /**
     * Gets the value of the defaultCacheBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultCacheBehavior }
     *     
     */
    public DefaultCacheBehavior getDefaultCacheBehavior() {
        return defaultCacheBehavior;
    }

    /**
     * Sets the value of the defaultCacheBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultCacheBehavior }
     *     
     */
    public void setDefaultCacheBehavior(DefaultCacheBehavior value) {
        this.defaultCacheBehavior = value;
    }

    /**
     * Gets the value of the cacheBehaviors property.
     * 
     * @return
     *     possible object is
     *     {@link CacheBehaviors }
     *     
     */
    public CacheBehaviors getCacheBehaviors() {
        return cacheBehaviors;
    }

    /**
     * Sets the value of the cacheBehaviors property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheBehaviors }
     *     
     */
    public void setCacheBehaviors(CacheBehaviors value) {
        this.cacheBehaviors = value;
    }

    /**
     * Gets the value of the customErrorResponses property.
     * 
     * @return
     *     possible object is
     *     {@link CustomErrorResponses }
     *     
     */
    public CustomErrorResponses getCustomErrorResponses() {
        return customErrorResponses;
    }

    /**
     * Sets the value of the customErrorResponses property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomErrorResponses }
     *     
     */
    public void setCustomErrorResponses(CustomErrorResponses value) {
        this.customErrorResponses = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the logging property.
     * 
     * @return
     *     possible object is
     *     {@link Logging }
     *     
     */
    public Logging getLogging() {
        return logging;
    }

    /**
     * Sets the value of the logging property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logging }
     *     
     */
    public void setLogging(Logging value) {
        this.logging = value;
    }

    /**
     * Gets the value of the priceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceClass() {
        return priceClass;
    }

    /**
     * Sets the value of the priceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceClass(String value) {
        this.priceClass = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnabled(String value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the viewerCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link ViewerCertificate }
     *     
     */
    public ViewerCertificate getViewerCertificate() {
        return viewerCertificate;
    }

    /**
     * Sets the value of the viewerCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewerCertificate }
     *     
     */
    public void setViewerCertificate(ViewerCertificate value) {
        this.viewerCertificate = value;
    }

    /**
     * Gets the value of the restrictions property.
     * 
     * @return
     *     possible object is
     *     {@link Restrictions }
     *     
     */
    public Restrictions getRestrictions() {
        return restrictions;
    }

    /**
     * Sets the value of the restrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Restrictions }
     *     
     */
    public void setRestrictions(Restrictions value) {
        this.restrictions = value;
    }

    /**
     * Gets the value of the webACLId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebACLId() {
        return webACLId;
    }

    /**
     * Sets the value of the webACLId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebACLId(String value) {
        this.webACLId = value;
    }

}
