//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.23 at 03:48:19 PM CDT 
//


package com.amazonaws.cloudfront.doc._2015_07_27;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DistributionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistributionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastModifiedTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InProgressInvalidationBatches" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DomainName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ActiveTrustedSigners" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}ActiveTrustedSignersType"/>
 *         &lt;element name="DistributionConfig" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}DistributionConfigType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributionType", propOrder = {
    "id",
    "status",
    "lastModifiedTime",
    "inProgressInvalidationBatches",
    "domainName",
    "activeTrustedSigners",
    "distributionConfig"
})
@XmlRootElement(name = "Distribution")
public class Distribution
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "LastModifiedTime", required = true)
    protected String lastModifiedTime;
    @XmlElement(name = "InProgressInvalidationBatches", required = true)
    protected String inProgressInvalidationBatches;
    @XmlElement(name = "DomainName", required = true)
    protected String domainName;
    @XmlElement(name = "ActiveTrustedSigners", required = true)
    protected ActiveTrustedSigners activeTrustedSigners;
    @XmlElement(name = "DistributionConfig", required = true)
    protected DistributionConfig distributionConfig;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the lastModifiedTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the lastModifiedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastModifiedTime(String value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the inProgressInvalidationBatches property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInProgressInvalidationBatches() {
        return inProgressInvalidationBatches;
    }

    /**
     * Sets the value of the inProgressInvalidationBatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInProgressInvalidationBatches(String value) {
        this.inProgressInvalidationBatches = value;
    }

    /**
     * Gets the value of the domainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * Sets the value of the domainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainName(String value) {
        this.domainName = value;
    }

    /**
     * Gets the value of the activeTrustedSigners property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveTrustedSigners }
     *     
     */
    public ActiveTrustedSigners getActiveTrustedSigners() {
        return activeTrustedSigners;
    }

    /**
     * Sets the value of the activeTrustedSigners property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveTrustedSigners }
     *     
     */
    public void setActiveTrustedSigners(ActiveTrustedSigners value) {
        this.activeTrustedSigners = value;
    }

    /**
     * Gets the value of the distributionConfig property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionConfig }
     *     
     */
    public DistributionConfig getDistributionConfig() {
        return distributionConfig;
    }

    /**
     * Sets the value of the distributionConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionConfig }
     *     
     */
    public void setDistributionConfig(DistributionConfig value) {
        this.distributionConfig = value;
    }

}
