//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.23 at 03:48:19 PM CDT 
//


package com.amazonaws.cloudfront.doc._2015_07_27;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DistributionSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistributionSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastModifiedTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DomainName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Aliases" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}AliasesType"/>
 *         &lt;element name="Origins" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}OriginsType"/>
 *         &lt;element name="DefaultCacheBehavior" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}DefaultCacheBehaviorType"/>
 *         &lt;element name="CacheBehaviors" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}CacheBehaviorsType"/>
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PriceClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Enabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ViewerCertificate" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}ViewerCertificateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributionSummaryType", propOrder = {
    "id",
    "status",
    "lastModifiedTime",
    "domainName",
    "aliases",
    "origins",
    "defaultCacheBehavior",
    "cacheBehaviors",
    "comment",
    "priceClass",
    "enabled",
    "viewerCertificate"
})
public class DistributionSummary
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "LastModifiedTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedTime;
    @XmlElement(name = "DomainName", required = true)
    protected String domainName;
    @XmlElement(name = "Aliases", required = true)
    protected Aliases aliases;
    @XmlElement(name = "Origins", required = true)
    protected Origins origins;
    @XmlElement(name = "DefaultCacheBehavior", required = true)
    protected DefaultCacheBehavior defaultCacheBehavior;
    @XmlElement(name = "CacheBehaviors", required = true)
    protected CacheBehaviors cacheBehaviors;
    @XmlElement(name = "Comment", required = true)
    protected String comment;
    @XmlElement(name = "PriceClass", required = true)
    protected String priceClass;
    @XmlElement(name = "Enabled", required = true)
    protected String enabled;
    @XmlElement(name = "ViewerCertificate", required = true)
    protected ViewerCertificate viewerCertificate;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the lastModifiedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the lastModifiedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedTime(XMLGregorianCalendar value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the domainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * Sets the value of the domainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainName(String value) {
        this.domainName = value;
    }

    /**
     * Gets the value of the aliases property.
     * 
     * @return
     *     possible object is
     *     {@link Aliases }
     *     
     */
    public Aliases getAliases() {
        return aliases;
    }

    /**
     * Sets the value of the aliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aliases }
     *     
     */
    public void setAliases(Aliases value) {
        this.aliases = value;
    }

    /**
     * Gets the value of the origins property.
     * 
     * @return
     *     possible object is
     *     {@link Origins }
     *     
     */
    public Origins getOrigins() {
        return origins;
    }

    /**
     * Sets the value of the origins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Origins }
     *     
     */
    public void setOrigins(Origins value) {
        this.origins = value;
    }

    /**
     * Gets the value of the defaultCacheBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultCacheBehavior }
     *     
     */
    public DefaultCacheBehavior getDefaultCacheBehavior() {
        return defaultCacheBehavior;
    }

    /**
     * Sets the value of the defaultCacheBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultCacheBehavior }
     *     
     */
    public void setDefaultCacheBehavior(DefaultCacheBehavior value) {
        this.defaultCacheBehavior = value;
    }

    /**
     * Gets the value of the cacheBehaviors property.
     * 
     * @return
     *     possible object is
     *     {@link CacheBehaviors }
     *     
     */
    public CacheBehaviors getCacheBehaviors() {
        return cacheBehaviors;
    }

    /**
     * Sets the value of the cacheBehaviors property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheBehaviors }
     *     
     */
    public void setCacheBehaviors(CacheBehaviors value) {
        this.cacheBehaviors = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the priceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceClass() {
        return priceClass;
    }

    /**
     * Sets the value of the priceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceClass(String value) {
        this.priceClass = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnabled(String value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the viewerCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link ViewerCertificate }
     *     
     */
    public ViewerCertificate getViewerCertificate() {
        return viewerCertificate;
    }

    /**
     * Sets the value of the viewerCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewerCertificate }
     *     
     */
    public void setViewerCertificate(ViewerCertificate value) {
        this.viewerCertificate = value;
    }

}
