//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.23 at 03:48:19 PM CDT 
//


package com.amazonaws.cloudfront.doc._2015_07_27;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DistributionListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistributionListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Marker" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaxItems" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="IsTruncated" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="Items">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Origin" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}OriginType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="DistributionSummary" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}DistributionSummaryType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributionListType", propOrder = {
    "marker",
    "maxItems",
    "isTruncated",
    "quantity",
    "items"
})
@XmlRootElement(name = "DistributionList")
public class DistributionList
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Marker", required = true)
    protected String marker;
    @XmlElement(name = "MaxItems")
    protected byte maxItems;
    @XmlElement(name = "IsTruncated", required = true)
    protected String isTruncated;
    @XmlElement(name = "Quantity")
    protected byte quantity;
    @XmlElement(name = "Items", required = true)
    protected DistributionList.Items items;

    /**
     * Gets the value of the marker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarker() {
        return marker;
    }

    /**
     * Sets the value of the marker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarker(String value) {
        this.marker = value;
    }

    /**
     * Gets the value of the maxItems property.
     * 
     */
    public byte getMaxItems() {
        return maxItems;
    }

    /**
     * Sets the value of the maxItems property.
     * 
     */
    public void setMaxItems(byte value) {
        this.maxItems = value;
    }

    /**
     * Gets the value of the isTruncated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTruncated() {
        return isTruncated;
    }

    /**
     * Sets the value of the isTruncated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTruncated(String value) {
        this.isTruncated = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public byte getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(byte value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionList.Items }
     *     
     */
    public DistributionList.Items getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionList.Items }
     *     
     */
    public void setItems(DistributionList.Items value) {
        this.items = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Origin" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}OriginType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="DistributionSummary" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}DistributionSummaryType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "origins",
        "distributionSummaries"
    })
    public static class Items
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "Origin")
        protected List<Origin> origins;
        @XmlElement(name = "DistributionSummary")
        protected List<DistributionSummary> distributionSummaries;

        /**
         * Gets the value of the origins property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the origins property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrigins().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Origin }
         * 
         * 
         */
        public List<Origin> getOrigins() {
            if (origins == null) {
                origins = new ArrayList<Origin>();
            }
            return this.origins;
        }

        /**
         * Gets the value of the distributionSummaries property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the distributionSummaries property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDistributionSummaries().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DistributionSummary }
         * 
         * 
         */
        public List<DistributionSummary> getDistributionSummaries() {
            if (distributionSummaries == null) {
                distributionSummaries = new ArrayList<DistributionSummary>();
            }
            return this.distributionSummaries;
        }

    }

}
