//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.23 at 03:48:19 PM CDT 
//


package com.amazonaws.cloudfront.doc._2015_07_27;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amazonaws.cloudfront.doc._2015_07_27 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amazonaws.cloudfront.doc._2015_07_27
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OriginsItemsType }
     * 
     */
    public OriginsItemsType createOriginsItemsType() {
        return new OriginsItemsType();
    }

    /**
     * Create an instance of {@link ViewerCertificate }
     * 
     */
    public ViewerCertificate createViewerCertificate() {
        return new ViewerCertificate();
    }

    /**
     * Create an instance of {@link Distribution }
     * 
     */
    public Distribution createDistribution() {
        return new Distribution();
    }

    /**
     * Create an instance of {@link AllowedMethods }
     * 
     */
    public AllowedMethods createAllowedMethods() {
        return new AllowedMethods();
    }

    /**
     * Create an instance of {@link CacheBehaviors }
     * 
     */
    public CacheBehaviors createCacheBehaviors() {
        return new CacheBehaviors();
    }

    /**
     * Create an instance of {@link Headers }
     * 
     */
    public Headers createHeaders() {
        return new Headers();
    }

    /**
     * Create an instance of {@link ActiveTrustedSigners.Items }
     * 
     */
    public ActiveTrustedSigners.Items createActiveTrustedSignersItems() {
        return new ActiveTrustedSigners.Items();
    }

    /**
     * Create an instance of {@link DefaultCacheBehavior }
     * 
     */
    public DefaultCacheBehavior createDefaultCacheBehavior() {
        return new DefaultCacheBehavior();
    }

    /**
     * Create an instance of {@link TrustedSigners }
     * 
     */
    public TrustedSigners createTrustedSigners() {
        return new TrustedSigners();
    }

    /**
     * Create an instance of {@link Cookies }
     * 
     */
    public Cookies createCookies() {
        return new Cookies();
    }

    /**
     * Create an instance of {@link DistributionConfig }
     * 
     */
    public DistributionConfig createDistributionConfig() {
        return new DistributionConfig();
    }

    /**
     * Create an instance of {@link Origin }
     * 
     */
    public Origin createOrigin() {
        return new Origin();
    }

    /**
     * Create an instance of {@link ForwardedValues }
     * 
     */
    public ForwardedValues createForwardedValues() {
        return new ForwardedValues();
    }

    /**
     * Create an instance of {@link TrustedSigners.Items }
     * 
     */
    public TrustedSigners.Items createTrustedSignersItems() {
        return new TrustedSigners.Items();
    }

    /**
     * Create an instance of {@link ActiveTrustedSigners.Items.Signer }
     * 
     */
    public ActiveTrustedSigners.Items.Signer createActiveTrustedSignersItemsSigner() {
        return new ActiveTrustedSigners.Items.Signer();
    }

    /**
     * Create an instance of {@link GeoRestriction }
     * 
     */
    public GeoRestriction createGeoRestriction() {
        return new GeoRestriction();
    }

    /**
     * Create an instance of {@link Aliases }
     * 
     */
    public Aliases createAliases() {
        return new Aliases();
    }

    /**
     * Create an instance of {@link AllowedMethods.Items }
     * 
     */
    public AllowedMethods.Items createAllowedMethodsItems() {
        return new AllowedMethods.Items();
    }

    /**
     * Create an instance of {@link DistributionList }
     * 
     */
    public DistributionList createDistributionList() {
        return new DistributionList();
    }

    /**
     * Create an instance of {@link DistributionSummary }
     * 
     */
    public DistributionSummary createDistributionSummary() {
        return new DistributionSummary();
    }

    /**
     * Create an instance of {@link Origins }
     * 
     */
    public Origins createOrigins() {
        return new Origins();
    }

    /**
     * Create an instance of {@link S3OriginConfig }
     * 
     */
    public S3OriginConfig createS3OriginConfig() {
        return new S3OriginConfig();
    }

    /**
     * Create an instance of {@link ActiveTrustedSigners.Items.Signer.KeyPairIds }
     * 
     */
    public ActiveTrustedSigners.Items.Signer.KeyPairIds createActiveTrustedSignersItemsSignerKeyPairIds() {
        return new ActiveTrustedSigners.Items.Signer.KeyPairIds();
    }

    /**
     * Create an instance of {@link CustomErrorResponses }
     * 
     */
    public CustomErrorResponses createCustomErrorResponses() {
        return new CustomErrorResponses();
    }

    /**
     * Create an instance of {@link com.amazonaws.cloudfront.doc._2015_07_27.Items }
     * 
     */
    public com.amazonaws.cloudfront.doc._2015_07_27.Items createItems() {
        return new com.amazonaws.cloudfront.doc._2015_07_27.Items();
    }

    /**
     * Create an instance of {@link CachedMethods.Items }
     * 
     */
    public CachedMethods.Items createCachedMethodsItems() {
        return new CachedMethods.Items();
    }

    /**
     * Create an instance of {@link ActiveTrustedSigners }
     * 
     */
    public ActiveTrustedSigners createActiveTrustedSigners() {
        return new ActiveTrustedSigners();
    }

    /**
     * Create an instance of {@link Restrictions }
     * 
     */
    public Restrictions createRestrictions() {
        return new Restrictions();
    }

    /**
     * Create an instance of {@link CachedMethods }
     * 
     */
    public CachedMethods createCachedMethods() {
        return new CachedMethods();
    }

    /**
     * Create an instance of {@link DistributionList.Items }
     * 
     */
    public DistributionList.Items createDistributionListItems() {
        return new DistributionList.Items();
    }

    /**
     * Create an instance of {@link Logging }
     * 
     */
    public Logging createLogging() {
        return new Logging();
    }

}
