//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.23 at 03:48:19 PM CDT 
//


package com.amazonaws.cloudfront.doc._2015_07_27;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OriginType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OriginType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DomainName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OriginPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="S3OriginConfig" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}S3OriginConfigType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginType", propOrder = {
    "id",
    "domainName",
    "originPath",
    "s3OriginConfig"
})
public class Origin
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "DomainName", required = true)
    protected String domainName;
    @XmlElement(name = "OriginPath", required = true)
    protected String originPath;
    @XmlElement(name = "S3OriginConfig", required = true)
    protected S3OriginConfig s3OriginConfig;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the domainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * Sets the value of the domainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainName(String value) {
        this.domainName = value;
    }

    /**
     * Gets the value of the originPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginPath() {
        return originPath;
    }

    /**
     * Sets the value of the originPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginPath(String value) {
        this.originPath = value;
    }

    /**
     * Gets the value of the s3OriginConfig property.
     * 
     * @return
     *     possible object is
     *     {@link S3OriginConfig }
     *     
     */
    public S3OriginConfig getS3OriginConfig() {
        return s3OriginConfig;
    }

    /**
     * Sets the value of the s3OriginConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link S3OriginConfig }
     *     
     */
    public void setS3OriginConfig(S3OriginConfig value) {
        this.s3OriginConfig = value;
    }

}
