//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.23 at 03:48:19 PM CDT 
//


package com.amazonaws.cloudfront.doc._2015_07_27;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RestrictionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RestrictionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GeoRestriction" type="{http://cloudfront.amazonaws.com/doc/2015-07-27/}GeoRestrictionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RestrictionsType", propOrder = {
    "geoRestriction"
})
public class Restrictions
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "GeoRestriction", required = true)
    protected GeoRestriction geoRestriction;

    /**
     * Gets the value of the geoRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link GeoRestriction }
     *     
     */
    public GeoRestriction getGeoRestriction() {
        return geoRestriction;
    }

    /**
     * Sets the value of the geoRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoRestriction }
     *     
     */
    public void setGeoRestriction(GeoRestriction value) {
        this.geoRestriction = value;
    }

}
