//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.23 at 03:48:19 PM CDT 
//


package com.amazonaws.cloudfront.doc._2015_07_27;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ViewerCertificateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViewerCertificateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CloudFrontDefaultCertificate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MinimumProtocolVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewerCertificateType", propOrder = {
    "cloudFrontDefaultCertificate",
    "minimumProtocolVersion"
})
public class ViewerCertificate
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CloudFrontDefaultCertificate", required = true)
    protected String cloudFrontDefaultCertificate;
    @XmlElement(name = "MinimumProtocolVersion", required = true)
    protected String minimumProtocolVersion;

    /**
     * Gets the value of the cloudFrontDefaultCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudFrontDefaultCertificate() {
        return cloudFrontDefaultCertificate;
    }

    /**
     * Sets the value of the cloudFrontDefaultCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudFrontDefaultCertificate(String value) {
        this.cloudFrontDefaultCertificate = value;
    }

    /**
     * Gets the value of the minimumProtocolVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumProtocolVersion() {
        return minimumProtocolVersion;
    }

    /**
     * Sets the value of the minimumProtocolVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumProtocolVersion(String value) {
        this.minimumProtocolVersion = value;
    }

}
