//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.14 at 10:25:25 AM EDT 
//


package com.servicemesh.agility.adapters.core.aws.security.group.resources;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescribeSecurityGroupsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescribeSecurityGroupsResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="securityGroupInfo" type="{http://ec2.amazonaws.com/doc/2013-10-15/}SecurityGroupSetType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescribeSecurityGroupsResponseType", propOrder = {
    "requestId",
    "securityGroupInfo"
})
@XmlRootElement(name = "DescribeSecurityGroupsResponseType")
public class DescribeSecurityGroupsResponseType {

    @XmlElement(required = true)
    protected String requestId;
    @XmlElement(required = true)
    protected SecurityGroupSetType securityGroupInfo;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the securityGroupInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityGroupSetType }
     *     
     */
    public SecurityGroupSetType getSecurityGroupInfo() {
        return securityGroupInfo;
    }

    /**
     * Sets the value of the securityGroupInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityGroupSetType }
     *     
     */
    public void setSecurityGroupInfo(SecurityGroupSetType value) {
        this.securityGroupInfo = value;
    }

}
