//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.14 at 10:25:25 AM EDT 
//


package com.servicemesh.agility.adapters.core.aws.security.group.resources;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IpPermissionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IpPermissionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ipProtocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fromPort" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="toPort" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="groups" type="{http://ec2.amazonaws.com/doc/2013-10-15/}UserIdGroupPairSetType"/>
 *         &lt;element name="ipRanges" type="{http://ec2.amazonaws.com/doc/2013-10-15/}IpRangeSetType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IpPermissionType", propOrder = {
    "ipProtocol",
    "fromPort",
    "toPort",
    "groups",
    "ipRanges"
})
@XmlRootElement(name = "IpPermissionType")
public class IpPermissionType {

    @XmlElement(required = true)
    protected String ipProtocol;
    protected Integer fromPort;
    protected Integer toPort;
    @XmlElement(required = true)
    protected UserIdGroupPairSetType groups;
    @XmlElement(required = true)
    protected IpRangeSetType ipRanges;

    /**
     * Gets the value of the ipProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpProtocol() {
        return ipProtocol;
    }

    /**
     * Sets the value of the ipProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpProtocol(String value) {
        this.ipProtocol = value;
    }

    /**
     * Gets the value of the fromPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFromPort() {
        return fromPort;
    }

    /**
     * Sets the value of the fromPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFromPort(Integer value) {
        this.fromPort = value;
    }

    /**
     * Gets the value of the toPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getToPort() {
        return toPort;
    }

    /**
     * Sets the value of the toPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setToPort(Integer value) {
        this.toPort = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link UserIdGroupPairSetType }
     *     
     */
    public UserIdGroupPairSetType getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserIdGroupPairSetType }
     *     
     */
    public void setGroups(UserIdGroupPairSetType value) {
        this.groups = value;
    }

    /**
     * Gets the value of the ipRanges property.
     * 
     * @return
     *     possible object is
     *     {@link IpRangeSetType }
     *     
     */
    public IpRangeSetType getIpRanges() {
        return ipRanges;
    }

    /**
     * Sets the value of the ipRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpRangeSetType }
     *     
     */
    public void setIpRanges(IpRangeSetType value) {
        this.ipRanges = value;
    }

}
