//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 11:31:27 AM CDT 
//


package com.amazonaws.elasticloadbalancing.doc._2012_06_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/}DescribeLoadBalancerPolicyTypesResult"/>
 *         &lt;element ref="{http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/}ResponseMetadata"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "describeLoadBalancerPolicyTypesResult",
    "responseMetadata"
})
@XmlRootElement(name = "DescribeLoadBalancerPolicyTypesResponse")
public class DescribeLoadBalancerPolicyTypesResponse {

    @XmlElement(name = "DescribeLoadBalancerPolicyTypesResult", required = true)
    protected DescribeLoadBalancerPolicyTypesResult describeLoadBalancerPolicyTypesResult;
    @XmlElement(name = "ResponseMetadata", required = true)
    protected ResponseMetadata responseMetadata;

    /**
     * Gets the value of the describeLoadBalancerPolicyTypesResult property.
     * 
     * @return
     *     possible object is
     *     {@link DescribeLoadBalancerPolicyTypesResult }
     *     
     */
    public DescribeLoadBalancerPolicyTypesResult getDescribeLoadBalancerPolicyTypesResult() {
        return describeLoadBalancerPolicyTypesResult;
    }

    /**
     * Sets the value of the describeLoadBalancerPolicyTypesResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescribeLoadBalancerPolicyTypesResult }
     *     
     */
    public void setDescribeLoadBalancerPolicyTypesResult(DescribeLoadBalancerPolicyTypesResult value) {
        this.describeLoadBalancerPolicyTypesResult = value;
    }

    /**
     * Gets the value of the responseMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMetadata }
     *     
     */
    public ResponseMetadata getResponseMetadata() {
        return responseMetadata;
    }

    /**
     * Sets the value of the responseMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMetadata }
     *     
     */
    public void setResponseMetadata(ResponseMetadata value) {
        this.responseMetadata = value;
    }

}
