//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 11:31:27 AM CDT 
//


package com.amazonaws.elasticloadbalancing.doc._2012_06_01;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amazonaws.elasticloadbalancing.doc._2012_06_01 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amazonaws.elasticloadbalancing.doc._2012_06_01
     * 
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link DescribeLoadBalancerPolicyTypesResponse }
     * 
     */
    public DescribeLoadBalancerPolicyTypesResponse createDescribeLoadBalancerPolicyTypesResponse() {
        return new DescribeLoadBalancerPolicyTypesResponse();
    }

    /**
     * Create an instance of {@link DescribeLoadBalancerPolicyTypesResult }
     * 
     */
    public DescribeLoadBalancerPolicyTypesResult createDescribeLoadBalancerPolicyTypesResult() {
        return new DescribeLoadBalancerPolicyTypesResult();
    }

    /**
     * Create an instance of {@link PolicyAttributeTypeDescription }
     * 
     */
    public PolicyAttributeTypeDescription createPolicyAttributeTypeDescription() {
        return new PolicyAttributeTypeDescription();
    }

    /**
     * Create an instance of {@link PolicyAttributeTypeDescriptions }
     * 
     */
    public PolicyAttributeTypeDescriptions createPolicyAttributeTypeDescriptions() {
        return new PolicyAttributeTypeDescriptions();
    }

    /**
     * Create an instance of {@link PolicyTypeDescription }
     * 
     */
    public PolicyTypeDescription createPolicyTypeDescription() {
        return new PolicyTypeDescription();
    }

    /**
     * Create an instance of {@link PolicyTypeDescriptions }
     * 
     */
    public PolicyTypeDescriptions createPolicyTypeDescriptions() {
        return new PolicyTypeDescriptions();
    }

    /**
     * Create an instance of {@link ResponseMetadata }
     * 
     */
    public ResponseMetadata createResponseMetadata() {
        return new ResponseMetadata();
    }    
}
