//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 11:31:27 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.amazonaws.elasticloadbalancing.doc._2012_06_01;
