//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.25 at 11:31:27 AM CDT 
//


package com.amazonaws.elasticloadbalancing.doc._2012_06_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 <p>
 *                     The <a>PolicyTypeDescription</a> data type.
 *                 </p>
 *             
 * 
 * <p>Java class for PolicyTypeDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyTypeDescription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PolicyTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PolicyAttributeTypeDescriptions" type="{http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/}PolicyAttributeTypeDescriptions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyTypeDescription", propOrder = {
    "policyTypeName",
    "description",
    "policyAttributeTypeDescriptions"
})
public class PolicyTypeDescription {

    @XmlElement(name = "PolicyTypeName")
    protected String policyTypeName;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "PolicyAttributeTypeDescriptions")
    protected PolicyAttributeTypeDescriptions policyAttributeTypeDescriptions;

    /**
     * Gets the value of the policyTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyTypeName() {
        return policyTypeName;
    }

    /**
     * Sets the value of the policyTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyTypeName(String value) {
        this.policyTypeName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the policyAttributeTypeDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyAttributeTypeDescriptions }
     *     
     */
    public PolicyAttributeTypeDescriptions getPolicyAttributeTypeDescriptions() {
        return policyAttributeTypeDescriptions;
    }

    /**
     * Sets the value of the policyAttributeTypeDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyAttributeTypeDescriptions }
     *     
     */
    public void setPolicyAttributeTypeDescriptions(PolicyAttributeTypeDescriptions value) {
        this.policyAttributeTypeDescriptions = value;
    }

}
